apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ewallet.fullname" . }}-init-seed-settings
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "ewallet.name" . }}
    helm.sh/chart: {{ template "ewallet.chart" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "22"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      name: {{ template "ewallet.fullname" . }}-init-seed-settings
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ template "ewallet.name" . }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-init-seed-settings
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bin/ewallet
            - seed
          args:
            - --settings
          env:
{{- /* ================================================ */}}
{{- /* Application Environment */}}
{{- /* ================================================ */}}
            - name: MIX_ENV
              value: prod
{{- /* ================================================ */}}
{{- /* Application Configuration */}}
{{- /* ================================================ */}}
            - name: EWALLET_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "ewallet.fullname" . }}
                  key: ewallet-secret-key
            - name: LOCAL_LEDGER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "ewallet.fullname" . }}
                  key: local-ledger-secret-key
{{- /* ================================================ */}}
{{- /* Database Configuration */}}
{{- /* ================================================ */}}
{{- if .Values.postgresql.enabled }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "ewallet.fullname" . }}-postgresql
                  key: ewallet-password
            - name: DATABASE_URL
              value: postgresql://ewallet:$(DATABASE_PASSWORD)@{{ template "postgresql.fullname" . }}/ewallet
            - name: LOCAL_LEDGER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "ewallet.fullname" . }}-postgresql
                  key: local-ledger-password
            - name: LOCAL_LEDGER_DATABASE_URL
              value: postgresql://ledger:$(LOCAL_LEDGER_DATABASE_PASSWORD)@{{ template "postgresql.fullname" . }}/local_ledger
{{- else }}
            - name: DATABASE_URL
              value: {{ required "ewalletDbUrl is required to be set" .Values.ewalletDbUrl | quote }}
            - name: LOCAL_LEDGER_DATABASE_URL
              value: {{ required "localLedgerDbUrl is required to be set" .Values.localLedgerDbUrl | quote }}
{{- end }}
{{- /* ================================================ */}}
{{- /* Monitoring */}}
{{- /* ================================================ */}}
{{- if .Values.sentryDsn | default "" | ne "" }}
            - name: SENTRY_DSN
              value: {{ .Values.sentryDsn }}
{{- end }}
{{- if .Values.appSignalPushApiKey | default "" | ne "" }}
            - name: APPSIGNAL_PUSH_API_KEY
              value: {{ .Values.appSignalPushApiKey }}
{{- end }}
{{- if .Values.appSignalAppEnv | default "" | ne "" }}
            - name: APPSIGNAL_APP_ENV
              value: {{ .Values.appSignalAppEnv }}
{{- end }}
{{- if .Values.appSignalVmMetrics | default "" | ne "" }}
            - name: METRICS
              value: {{ .Values.appSignalVmMetrics | quote }}
{{- end }}
{{- with .Values.image.pullSecrets }}
      imagePullSecrets:
{{ toYaml . | trim | indent 8 }}
{{- end }}
